# Generated by Django 5.0 on 2024-04-18 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('description', models.TextField()),
                ('technology', models.CharField(max_length=140)),
                ('image', models.FileField(blank=True, upload_to='assignment_images/')),
            ],
        ),
    ]
