# Generated by Django 5.0 on 2024-04-14 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='decription',
            new_name='description',
        ),
    ]
