# Generated by Django 5.0 on 2024-04-15 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_decription_task_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.FileField(blank=True, upload_to='task_images/'),
        ),
    ]
